version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: 'student'
      POSTGRES_USER: 'student'
      POSTGRES_DB: 'kupipodariday'
    ports:
      - 5436:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
